# Generated by Django 3.1 on 2020-08-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200820_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilee',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilee',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
