# Generated by Django 3.1 on 2020-08-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profilee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilee',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
